exports.books =  {currently: [{title: "Crooked Little Vein",
                               author: "Warren Ellis",
                               recommender: "Toeless Bob",
                               img: "images/crooked.jpeg"}],
                  read: [{title: "The Big Short: Inside The Doomsday Machine",
                          author: "Michael Lewis",
                          recommender: "Herr Autoflatulence",
                          img: "images/the-big-short.jpeg"},
                         {title: "Brightness Reef (Uplift Storm Trilogy, #1)",
                          author: "David Brin",
                          recommender: "Clint Eastwood",
                          img: "images/reef.jpeg"} ],
                  queue: [{title: "The Demon-Haunted World: Science As A Candle In The Darkness",
                           author: "Carl Sagan",
                           recommender: "Señor Pants",
                           img: "images/demon.jpeg"}, 
                          {title: "Bitter Seeds",
                           author: "Ian Tregillis",
                           recommender: "Captain Jackass Bojangles",
                           img: "images/seeds.jpg"}]
};
